version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: "timescale"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db-data:
    driver: local